### ISSUE TITLE
BUG: New Class Unlocked, Perks Missing

### ISSUE THREAD

**Issue by Tay-Sike** [stimm4711/GloomhavenCampaignTracker#4]
I just unlocked the second to last class of your list of "Unlocked Classes", the Triforce symbol, but the perks page of the character has no perks listed.

**Possible replication of the bug:**

From the _Characters_ page, create a currently locked character. Then edit the character from any page that allows editing. The **add perk** page, on the _Perks_ page, will be empty.

After officially unlocking the character on the _Unlocks_ page, I am still unable to view the listed perks for the specified class.

**Note:**
Haven't tested with other locked classes yet.

**Comment by stimm4711** [comment]
I've tried to reproduce this issue but the perks are always shown in the selection. 
It would be helpfull to know, on what device you have this issue. And it would be great, if I could get a copy of the database backup to see if the update went wrong. Maybe you could give me a link to download it from dropbox, google drive or one drive?

**Comment by stimm4711** [comment]
Should be fixed with update 1.3.4 released today

**Comment by Tay-Sike** [comment]
Hello,

I apologize for not sending this earlier. I meant to send it to you but I
seemed to forget. This is the backup of my version of
GloomhavenCampaignTracker.

  20180915_13-35-24_GloomhavenCampaignTracker.db3
<https://drive.google.com/file/d/1QaV6vfJ4031LJIm6EiaRg5HCCfsdX5Ag/view?usp=drivesdk>

**Comment by stimm4711** [comment]
No problem. I found the bug and with update 1.3.4 that I released today I should be fixed.


________________________________
Von: Tay-Sike <notifications@github.com>
Gesendet: Wednesday, September 26, 2018 8:29:48 PM
An: stimm4711/GloomhavenCampaignTracker
Cc: timmi; State change
Betreff: Re: [stimm4711/GloomhavenCampaignTracker] BUG: New Class Unlocked, Perks Missing (#4)

Hello,

I apologize for not sending this earlier. I meant to send it to you but I
seemed to forget. This is the backup of my version of
GloomhavenCampaignTracker.

20180915_13-35-24_GloomhavenCampaignTracker.db3
<https://drive.google.com/file/d/1QaV6vfJ4031LJIm6EiaRg5HCCfsdX5Ag/view?usp=drivesdk>

**Comment by Tay-Sike** [comment]
Can confirm that it is now fixed. Thank you!

**Comment by bschnur** [comment]
I have this issue on 1.3.8. Same class; unlocked then created character, went to add perks, no perks from which to select. I've backed up the DB and restored, issue persists.

Link to backup file on Google Drive: https://drive.google.com/file/d/1L1ahbB2hGmQvAbEobqW3YUDeixMgnCpz/view?usp=drivesdk

I'm running the app on a Pixel 2 XL, Android version 9, build number PQ1A.181105.017.A1

**Comment by stimm4711** [comment]
Thank you for the database. Looks like an update went wrong and didn't add the class perks. I'll add an update of the class perks in the next update. I hope that will fix it for you.

**Comment by stimm4711** [comment]
Update 1.3.9 is uploaded and should be available soon. Please let me know if it worked.

**Comment by bschnur** [comment]
Fixed! Kudos for the super-quick turnaround.
